name: Build UI

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          dir: 'frontend'
          cmd: install
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          dir: 'frontend'
          cmd: build

      - name: Archive Built UI
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: frontend/dist
