name: Build

on:
  push:
    branches: [ "master", "develop" ]
    tags:
      - '*'

jobs:
  build-ui:
    name: Build UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          dir: 'frontend'
          cmd: install

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          dir: 'frontend'
          cmd: build

      - name: Cache Built UI
        uses: actions/cache@v3
        id: frontend-dist
        with:
          path: frontend/dist/*
          key: ${{ github.sha }}

  build-docker:
    name: Build Docker Container
    runs-on: ubuntu-latest
    needs: [build-ui]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: restore-build
        with:
          path: frontend/dist/*
          key: ${{ github.sha }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: deathcamel57/nginx-proxy-manager

      # If we're on master branch, build latest
      - if: github.ref == 'refs/heads/master'
        name: Build the Docker image
        run: docker build . --file ./docker/Dockerfile --tag deathcamel57/nginx-proxy-manager:latest

      # If we're on develop branch, build dev
      - if: github.ref == 'refs/heads/develop'
        name: Build the Docker image
        run: docker build . --file ./docker/Dockerfile --tag deathcamel57/nginx-proxy-manager:dev

      # If this is a tagged release, build tag
      - if: startsWith(github.ref, 'refs/tags/')
        name: Build the Docker image
        run: docker build . --file ./docker/Dockerfile --tag deathcamel57/nginx-proxy-manager:${{ github.ref_name }}

      - if: github.ref == 'refs/heads/master'
        name: Push to Docker Hub
        run: docker push deathcamel57/nginx-proxy-manager:latest

      - if: github.ref == 'refs/heads/develop'
        name: Push to Docker Hub
        run: docker push deathcamel57/nginx-proxy-manager:dev

      - if: startsWith(github.ref, 'refs/tags/')
        name: Push to Docker Hub
        run: docker push deathcamel57/nginx-proxy-manager:${{ github.ref_name }}
